# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR"

reviews:
  profile: "assertive"
  high_level_summary: true
  path_filters:
    - '**/package-lock.json'
    - '**/*.log'
    - 'docs/**/*'
    - "**/*.md"
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.png"
    - "**/*.svg"
    - "**/*.gif"