language: "ko-KR"

reviews:
  profile: "assertive"
  high_level_summary: true

exclude:
  - '**/package-lock.json'
  - '**/*.log'
  - 'docs/**/*'
  - "**/*.md"

exclude_file_types:
  - '.jpg'
  - '.jpeg'
  - '.png'
  - '.svg'
  - '.gif'