spring:
  application:
    name: fittura
  profiles:
    active: dev
    include: local
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:h2:mem:db_dev;MODE=MySQL
    username: sa
    password:
  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.springframework.transaction.interceptor: INFO
jwt:
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

app:
  cookie:
    refresh-token-name: "refreshToken"
    path: "/"
    secure: false
    http-only: true
    same-site: "Strict"
