spring:
  datasource:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
