spring:
  datasource:
    url: jdbc:tc:mysql:8.0:///fittura_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.fittura: DEBUG