---
name: PR 자동화

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  pr-automation:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - name: PR 작성자를 담당자로 할당
        uses: li-sumup/actions-assigner@v1.0.2

      - name: bug 라벨 추가
        if: ${{ startsWith(github.event.pull_request.title, '[Fix]') || startsWith(github.event.pull_request.title, '[fix]')}}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug

      - name: chore 라벨 추가
        if: ${{ startsWith(github.event.pull_request.title, '[Chore]') || startsWith(github.event.pull_request.title, '[chore]')}}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: chore

      - name: feature 라벨 추가
        if: ${{ startsWith(github.event.pull_request.title, '[Feat]') || startsWith(github.event.pull_request.title, '[feat]') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: feature

      - name: refactor 라벨 추가
        if: ${{ startsWith(github.event.pull_request.title, '[Refactor]') || startsWith(github.event.pull_request.title, '[refactor]') }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: refactor
